const picMapping = {
  "Penggantian Slip Ring (Stainless Steel)": "Elektrik",
  "Penambahan Brush Holder 1 Set": "Elektrik",
  "Pengukuran dan Penggantian Carbon Brush (Standar 42 mm)": "Elektrik",
  "Inspeksi dan Pemeriksaan Motor Blower Motor Blower (Dial & Shaking)": "Elektrik",
  "Penggantian Bearing Setiap 1,5 Tahun": "Tim PRL & Tim Revisi",
  "Join Inspection dengan DC THN": "Tim Flying Gang",
  "21 serie Modifikasi bearing housing kedua sisi": "Tim PRL",
  "Penggantian Impeler (21 Series) dengan bahan yang lebih ringan": "Tim PRL",
  "Flushing Fuel Setiap 12 Bulan": "Engine",
  "Drain BBM 1L setiap Perawatan": "Engine",
  "Pemeriksaan Ring Piston Setiap P3": "Engine",
  "Pemeriksaan Piston Cooling Pipe Pada Saat Perawatan Pertama di 2025": "Engine",
  "Pemeriksaan & Inspeksi Piston Cooling Pipe & Seal P12": "Engine",
  "Instal Ulang Software IPM P12": "Elektrik",
  "Pengecekan kondisi IPM & Test Air Brake": "Elektrik",
  "Periksa dan Pembersihan Komponen Internal IPM setiap 3 Tahun": "Elektrik",
  "Memastikan proses pengelasan sesuai Prosedur dari PRL": "PRL",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan IPM": "Tim Flying Gang",
  "Instal Ulang Software EM2000 setiap 3 Tahun": "Elektrik",
  "Pengecekan & Pembersihan EM2000": "Elektrik",
  "Recycle ALL CB sampai Battery tunggu 1 Minute P1": "Tim Flying Gang",
  "Pemeriksaan dan Pengamanan Kabel Traction Alternator dari Cacat atau Rubbing": "Elektrik",
  "Pemasangan Cooling Fan pada PSM Compartment": "Elektrik",
  "Pengecekan dan Pembersihan kondisi PSM": "Tim Flying Gang",
  "Reposisi Resistor oleh PRL": "PRL",
  "Pengecekan kabel High Voltage pada CT A,B,C di Alternator": "Elektrik",
  "Pengecekan shield kabel PSM": "Elektrik",
  "Inspeksi Sistem Pendingan E Locker Setiap Perawatan": "Tim Flying Gang",
  "Melakukan Pengecekan, Pembersihan Phase Module seluruh lokomotif": "Elektrik",
  "Periksa sikuit dari ground setiap Perawatan": "Elektrik",
  "Instal Ulang Software PCM 500 setiap 3 Tahun": "Elektrik",
  "Pengecekan & Pembersihan PCM 500 Setiap Perawatan": "Elektrik",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan": "Tim Flying Gang",
  "Pemeriksaan Low Voltage Ground setiap bulan": "Tim Flying Gang",
  "Periksa ground AC setiap perawatan": "Tim Self Test",
  "Pengecekan fungsi dan kondisi CLOPS setiap Bulan": "Tim Flying Gang & Angin",
  "Pengecekan Kebocoran & Volume Pelumas setiap Bulan": "Tim Flying Gang & Angin",
  "Pemeriksaan Kondisi Terminal EFCO L & R Setiap Perawatan": "Elektrik",
  "Pengecekan & Penggantian Matras EFCO": "Elektrik",
  "Pengecekan semua kondisi Pipa Water Pump setiap Bulan": "Engine",
  "Melakukan Pemantauan tekanan in dan out melalui Parameter Uptime": "Engine",
  "Pengecekan dan Penggantian Mur (Jika Sudah Maksimal)": "Engine",
  "Pemeriksaan Posisi Coupling setiap Bulan": "Engine",
  "Pengecekan Semua Kondisi Flexible Hose setiap Bulan": "Tim Flying Gang",
  "Penggantian setiap 3 Tahun": "Engine",
  "Pengecekan semua kondisi PLUG PD2": "Tim Flying Gang",
  "Pemeriksaan Kondisi BPCP setiap Bulan": "Tim Flying Gang & Angin",
  "Reload EPCU Software P36": "Elektrik",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan BPCP": "Tim Flying Gang",
  "Drain Manual MR setiap Bulan": "Tim Flying Gang & Angin",
  "Instal Ulang MPU Setiap setiap 3 Tahun": "Elektrik",
  "Pengecekan dan Pembersihan MPU setiap perawatan": "Elektrik",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan MPU": "Tim Flying Gang",
  "Pengecekan dan Pembersihan PSU 500 Setiap Perawatan": "Elektrik",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan PSU 500": "Tim Flying Gang",
  "Pemeriksaan Kondisi Turbocharger (Mur, Baut, TPURPM)": "Engine",
  "Pemeriksaan GAP Clearence Impeler Air Inlet Setiap Perawatan": "Engine",
  "Pengecekan dan pengukuran Fuel Pump Setiap Perawatan": "Elektrik",
  "Flushing Fuel Setiap 12 Bulan (FP)": "Engine",
  "Pengecekan dan Penggantian Komponen Wiper (Blade, Cup Nut, Baut) setiap Bulan": "Tim Flying Gang & Angin",
  "Setup Langkah Blade setiap Bulan": "Tim Flying Gang & Angin",
  "Pengecekan Semua Komponen Pemasir": "Tim Flying Gang & Truck",
  "Pengecekan dan Pembersihan MPIO Setiap Perawatan": "Tim Flying Gang",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan MPIO": "Tim Flying Gang",
  "Reload EPCU Software setiap 36 Bulan (MPIO)": "Elektrik",
  "Pengecekan Semua Kondisi Relay GR & Koneksinya": "Tim Flying Gang",
  "Melakukan Ground Test semua lokomotif saat perawatan": "Elektrik"
};

function getPIC(detailAktivitas) {
  return picMapping[detailAktivitas] || "Tidak Diketahui";
}

module.exports = { getPIC, picMapping };
