// Mapping detailAktivitas (leading indicator) ke PIC/tim Action Plan
// Sumber: mapping user
const detailAktivitasToPic = {
  "Penggantian Slip Ring (Stainless Steel)": "TIM ELEKTRIK",
  "Penambahan Brush Holder 1 Set": "TIM ELEKTRIK",
  "Pengukuran dan Penggantian Carbon Brush (Standar 42 mm)": "TIM ELEKTRIK",
  "Inspeksi dan Pemeriksaan Motor Blower (Dial & Shaking)": "TIM ELEKTRIK",
  "Penggantian Bearing Setiap 1,5 Tahun": "TIM PRL",
  "Join Inspection dengan DC THN": "TIM FLYING GANG",
  "21 serie Modifikasi bearing housing kedua sisi": "TIM PRL",
  "Penggantian Impeler (21 Series) dengan bahan yang lebih ringan": "TIM PRL",
  "Flushing Fuel Setiap Perawatan": "TIM ENGINE",
  "Drain BBM 1L setiap Perawatan": "TIM ENGINE",
  "Pemeriksaan Ring Piston Setiap P3": "TIM ENGINE",
  "Pemeriksaan Piston Cooling Pipe Pada Saat Perawatan Pertama di 2025": "TIM ENGINE",
  "Pemeriksaan & Inspeksi Piston Cooling Pipe & Seal P12": "TIM ENGINE",
  "Instal Ulang Software IPM P12": "TIM ELEKTRIK",
  "Pengecekan kondisi IPM & Test Air Brake": "TIM ELEKTRIK",
  "Periksa dan Pembersihan Komponen Internal IPM setiap 3 Tahun": "TIM ELEKTRIK",
  "Memastikan proses pengelasan sesuai Prosedur dari PRL": "TIM PRL",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan IPM": "TIM FLYING GANG",
  "Instal Ulang Software EM2000 setiap 3 Tahun": "TIM ELEKTRIK",
  "Pengecekan & Pembersihan EM2000": "TIM ELEKTRIK",
  "Recycle ALL CB sampai Battery tunggu 1 Minute P1": "TIM FLYING GANG",
  "Pemeriksaan dan Pengamanan Kabel Traction Alternator dari Cacat atau Rubbing": "TIM ELEKTRIK",
  "Pemasangan Cooling Fan pada PSM Compartment": "TIM ELEKTRIK",
  "Pengecekan dan Pembersihan kondisi PSM": "TIM ELEKTRIK",
  "Reposisi Resistor oleh PRL": "TIM PRL",
  "Pengecekan kabel High Voltage pada CT A,B,C di Alternator": "TIM ELEKTRIK",
  "Pengecekan shield kabel PSM": "TIM ELEKTRIK",
  "Inspeksi Sistem Pendingan E Locker Setiap Perawatan": "TIM ELEKTRIK",
  "Melakukan Pengecekan, Pembersihan Phase Module seluruh lokomotif": "TIM ELEKTRIK",
  "Periksa sikuit dari ground setiap Perawatan": "TIM SELF TEST",
  "Instal Ulang Software PCM 500 setiap 3 Tahun": "TIM ELEKTRIK",
  "Pengecekan & Pembersihan PCM 500 Setiap Perawatan": "TIM ELEKTRIK",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan": "TIM FLYING GANG",
  "Pemeriksaan Low Voltage Ground setiap bulan": "TIM ELEKTRIK",
  "Periksa ground AC setiap perawatan": "TIM SELF TEST",
  "Pengecekan fungsi dan kondisi CLOPS setiap Bulan": "TIM FLYING GANG & ANGIN",
  "Pengecekan Kebocoran & Volume Pelumas setiap Bulan": "TIM FLYING GANG & ANGIN",
  "Pembuatan alat DC LINK berbasis IoT (Daily Checker Locomotive Integrated NetworK)": "TIM 8",
  "Pemeriksaan Kondisi Terminal EFCO L & R Setiap Perawatan": "TIM ELEKTRIK",
  "Pengecekan & Penggantian Matras EFCO": "TIM ELEKTRIK",
  "Pengecekan semua kondisi Pipa Water Pump setiap Bulan": "TIM ENGINE",
  "Melakukan Pemantauan tekanan in dan out melalui Parameter Uptime": "TIM ENGINE",
  "Pengecekan dan Penggantian Mur (Jika Sudah Maksimal)": "TIM ENGINE",
  "Pemeriksaan Posisi Coupling setiap Bulan": "TIM ENGINE",
  "Pengecekan Semua Kondisi Flexible Hose setiap Bulan": "TIM FLYING GANG",
  "Penggantian setiap 3 Tahun": "TIM REVISI",
  "Pengecekan semua kondisi PLUG PD2": "TIM FLYING GANG",
  "Pemeriksaan Kondisi BPCP setiap Bulan": "TIM FLYING GANG & ANGIN",
  "Reload EPCU Software P36": "TIM ELEKTRIK",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan BPCP": "TIM FLYING GANG",
  "Drain Manual MR setiap Bulan": "TIM FLYING GANG & ANGIN",
  "Instal Ulang MPU Setiap setiap 3 Tahun": "TIM ELEKTRIK",
  "Pengecekan dan Pembersihan MPU setiap perawatan": "TIM ELEKTRIK",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan MPU": "TIM FLYING GANG",
  "Pengecekan dan Pembersihan PSU 500 Setiap Perawatan": "TIM ELEKTRIK",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan PSU 500": "TIM FLYING GANG",
  "Pemeriksaan Kondisi Turbocharger (Mur, Baut, TPURPM)": "TIM ENGINE",
  "Pemeriksaan GAP Clearence Impeler Air Inlet Setiap Perawatan": "TIM ENGINE",
  "Pengecekan dan pengukuran Fuel Pump Setiap Perawatan": "TIM ENGINE",
  "Flushing Fuel Setiap Perawatan (FP)": "TIM ENGINE",
  "Pengecekan dan Penggantian Komponen Wiper (Blade, Cup Nut, Baut) setiap Bulan": "TIM FLYING GANG",
  "Setup Langkah Blade setiap Bulan": "TIM FLYING GANG",
  "Pengecekan Semua Komponen Pemasir": "TIM FLYING GANG & TRUCK",
  "Pengecekan dan Pembersihan MPIO Setiap Perawatan": "TIM FLYING GANG",
  "Recyce ALL CB sampai Battery tunggu 1 Minute setiap Bulan MPIO": "TIM FLYING GANG",
  "Reload EPCU Software setiap 36 Bulan (MPIO)": "TIM ELEKTRIK",
  "Pengecekan Semua Kondisi Relay GR & Koneksinya": "TIM FLYING GANG",
  "Melakukan Ground Test semua lokomotif saat perawatan": "TIM ELEKTRIK",
  "Melakukan Pengukuran Roda Periode 1 Bulan": "TIM TRUCK",
  "Melakukan Pengecekan Suhu Bearing": "TIM ENGINE",
  "Pengecekan Seal Cap (Tidak Meler/Rusak)": "TIM ENGINE",
  "Pengecekan Baut End Cup Kencang dan Lengkap": "TIM ENGINE"
};

export default detailAktivitasToPic;
